---
# tasks file for http

- name: Install http
  yum:
    name: httpd
    state: latest

- name: Configure httpd
  template:
    src: etc/httpd/conf/httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: root
    mode: '0644'

- name: Start httpd
  systemd:
    state: restarted
    name: httpd
